# Generated by Django 2.1.3 on 2018-11-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_name', models.CharField(max_length=100)),
                ('motion_category', models.CharField(max_length=100)),
                ('value_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=100)),
                ('robot_category', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_num', models.IntegerField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='robocms.Motion')),
            ],
        ),
        migrations.AddField(
            model_name='motion',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robocms.Robot'),
        ),
    ]
